export const mainList = [{"id":1,"code":"https://prod.spline.design/1K5Q-tNaVrfPjwqg/scene.splinecode", "www":"https://apple.com", "twitter":"https://x.com"}, 
    {"id":2,"code":"https://prod.spline.design/1K5Q-tNaVrfPjwqg/scene.splinecode", "www":"https://apple.com", "twitter":"https://x.com"}, 
    {"id":3,"code":"https://prod.spline.design/1K5Q-tNaVrfPjwqg/scene.splinecode", "www":"https://apple.com", "twitter":"https://x.com"}, 
    {"id":4,"code":"https://prod.spline.design/1K5Q-tNaVrfPjwqg/scene.splinecode", "www":"https://apple.com", "twitter":"https://x.com"}, 
    {"id":5,"code":"https://prod.spline.design/1K5Q-tNaVrfPjwqg/scene.splinecode", "www":"https://apple.com", "twitter":"https://x.com"}, 
    {"id":6,"code":"https://prod.spline.design/1K5Q-tNaVrfPjwqg/scene.splinecode", "www":"https://apple.com", "twitter":"https://x.com"}, 
    {"id":7,"code":"https://prod.spline.design/1K5Q-tNaVrfPjwqg/scene.splinecode", "www":"https://apple.com", "twitter":"https://x.com"}, 
    {"id":8,"code":"https://prod.spline.design/1K5Q-tNaVrfPjwqg/scene.splinecode", "www":"https://apple.com", "twitter":"https://x.com"}, 
    {"id":9,"code":"https://prod.spline.design/1K5Q-tNaVrfPjwqg/scene.splinecode", "www":"https://apple.com", "twitter":"https://x.com"}, 
    {"id":10,"code":"https://prod.spline.design/1K5Q-tNaVrfPjwqg/scene.splinecode", "www":"https://apple.com", "twitter":"https://x.com"}]; // Change or Add new spline code and Website link + twitter here DO NOT CHANGE ID